"""
Game Intelligence Synthesizer - Phase 3

Converts Master-JSON from Phase 2 AI Analysis into high-quality synthesized reports.
Uses Gemini Pro for intelligent synthesis with structured Markdown output.
"""

import logging
from datetime import datetime
from typing import Dict, List, Any, Optional
import json

from ..infrastructure.llm_client import GeminiClient
from ....models.synthesis_models import SynthesisInput, SynthesisOutput, SynthesisAnalysis


logger = logging.getLogger(__name__)


class synthesizer:
    """Synthesizes AI analysis outputs into comprehensive reports."""
    
    def __init__(self):
        """Initialize synthesizer with Gemini client."""
        self.gemini_client = GeminiClient()
        
        self.synthesis_prompt_template = """
You are an expert game analyst and intelligence reporter. Your task is to synthesize multiple AI analyses into a comprehensive, high-quality report.

## INPUT DATA
You are receiving AI analyses from 4 macro-skill services analyzing the game "{game_name}":

1. **Design & Art** - Visual aesthetics, art direction, design patterns
2. **User Experience** - Player interface, usability, engagement mechanics  
3. **Technology Systems** - Technical architecture, performance, platforms
4. **Strategy & Market** - Business model, market positioning, competitive analysis

## ANALYSIS DATA
{macro_skill_analyses}

## YOUR TASK
Create a comprehensive game intelligence report with:

### Executive Summary (150-200 words)
- Game overview and classification
- Key strengths and differentiators
- Market opportunities and challenges
- Overall assessment and rating

### Detailed Analysis Sections
For each macro-skill with specific insights:
- **Design & Art Analysis**
- **User Experience Analysis** 
- **Technology Systems Analysis**
- **Strategy & Market Analysis**

### Cross-Skill Insights
- Connections between design and user experience
- Technical implications for market strategy
- User experience's impact on commercial success
- Design patterns affecting technical architecture

### Strategic Recommendations
- Key opportunities for improvement
- Market positioning strategies
- Roadmap suggestions for updates/expansions
- Technical optimization priorities

### competitive Landscape
- Position against similar games
- Unique value propositions
- Market gap opportunities

## OUTPUT REQUIREMENTS
- Write in professional, insightful tone
- Use specific examples from the analysis data
- Include data-driven insights, not generic statements  
- Format as clean Markdown with proper headers
- Add bullet points for key findings
- Include confidence levels where appropriate
- Aim for 1500-2500 words total

## FORMAT
```markdown
# Game Intelligence Report: {game_name}

*Generated on {timestamp}*

---

## 📊 Executive Summary

[Your comprehensive summary here]

---

## 🎨 Design & Art Analysis

[Design & Art insights with specific findings]

---

## 👥 User Experience Analysis  

[User Experience insights with specific findings]

---

## ⚙️ Technology Systems Analysis

[Technology insights with specific findings]

---

## 📈 Strategy & Market Analysis

[Market insights with specific findings]

---

## 🔗 Cross-Skill Insights

[Connections between different areas]

---

## 🎯 Strategic Recommendations

[Actionable recommendations]

---

## 🏆 Competitive Landscape

[Competitive analysis and positioning]

---

## 📋 Analysis Summary

| Aspect | Rating | Confidence | Key Findings |
|--------|--------|------------|-------------|
| Design & Art | [A-F] | [High/Med/Low] | [2-3 key points] |
| User Experience | [A-F] | [High/Med/Low] | [2-3 key points] |
| Technology Systems | [A-F] | [High/Med/Low] | [2-3 key points] |
| Strategy & Market | [A-F] | [High/Med/Low] | [2-3 key points] |

---

*Report generated by GetSmart AI Game Intelligence System*
```
"""

    def _format_macro_skill_analyses(self, macro_skill_analyses: List[Dict[str, Any]]) -> str:
        """Format macro-skill analyses for the synthesis prompt."""
        formatted_analyses = []
        
        for i, raw_analysis in enumerate(macro_skill_analyses, 1):
            if isinstance(raw_analysis, dict):
                analysis = dict(raw_analysis)
            else:
                analysis = {
                    "skill_name": f"Analysis {i}",
                    "status": "unknown",
                    "confidence_score": 0.7,
                    "analysis_text": str(raw_analysis),
                    "content": {},
                }

            skill_name = analysis.get("skill_name", f"Analysis {i}")
            content = analysis.get("content", {})
            if not isinstance(content, dict):
                content = {}

            analysis_text = analysis.get("analysis_text", "No analysis text available")
            if not isinstance(analysis_text, str):
                analysis_text = str(analysis_text)

            confidence_score = analysis.get("confidence_score", 0.7)
            try:
                confidence_score = float(confidence_score)
            except (TypeError, ValueError):
                confidence_score = 0.7
            
            formatted_analysis = f"""
### {i}. {skill_name}
**Status:** {analysis.get("status", "unknown")}
**Confidence:** {confidence_score:.1%}

**Raw Analysis:**
```
{analysis_text}
```

**Key Insights:**
"""
            
            # Extract key insights from content structure
            if isinstance(content, dict):
                for key, value in content.items():
                    if isinstance(value, str) and len(value) > 20:
                        formatted_analysis += f"**{key.replace('_', ' ').title()}:** {value}\n"
                    elif isinstance(value, dict):
                        for sub_key, sub_value in value.items():
                            if isinstance(sub_value, str) and len(sub_value) > 20:
                                formatted_analysis += f"**{sub_key.replace('_', ' ').title()}:** {sub_value}\n"
            
            formatted_analyses.append(formatted_analysis)
        
        return "\n".join(formatted_analyses)

    def _extract_confidence_info(self, macro_skill_analyses: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Extract confidence and quality information from analyses."""
        confidences: list[float] = []
        total_confidence = 0.0
        skill_confidences: dict[str, float] = {}
        
        for raw_analysis in macro_skill_analyses:
            if isinstance(raw_analysis, dict):
                analysis = raw_analysis
            else:
                analysis = {"confidence_score": 0.7, "skill_name": "Unknown"}

            confidence_value = analysis.get("confidence_score", 0.7)
            try:
                confidence = float(confidence_value)
            except (TypeError, ValueError):
                confidence = 0.7

            skill_name = analysis.get("skill_name", "Unknown")
            if not isinstance(skill_name, str):
                skill_name = str(skill_name)

            confidences.append(confidence)
            total_confidence += confidence
            skill_confidences[skill_name] = confidence
        
        average_confidence = total_confidence / len(confidences) if confidences else 0.0
        
        return {
            "average_confidence": average_confidence,
            "skill_confidences": skill_confidences,
            "confidence_distribution": {
                "high": sum(1 for c in confidences if c > 0.8),
                "medium": sum(1 for c in confidences if 0.6 <= c <= 0.8),
                "low": sum(1 for c in confidences if c < 0.6),
                "total": len(confidences)
            }
        }

    def _create_fallback_report(self, master_json: Dict[str, Any]) -> str:
        """Create a fallback structured report when synthesis fails."""
        game_info = master_json.get("game_info", {})
        analyses = master_json.get("macro_skill_analyses", [])
        
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
        
        report = f"""# Game Intelligence Report: {game_info.get('game_name', 'Unknown Game')}

*Generated on {timestamp}*  

**⚠️ Note:** This is a fallback report generated due to synthesis issues. The detailed synthesis is temporarily unavailable.

---

## 📊 Game Overview

**Game:** {game_info.get('game_name', 'Unknown')}  
**Analysis ID:** {game_info.get('game_id', 'Unknown')}  
**Analysis Date:** {game_info.get('analysis_timestamp', timestamp)}  
**Pipeline Success Rate:** {game_info.get('success_rate', 0):.1%}

---

## 🎨 Design & Art Analysis

"""
        
        # Add each macro-skill analysis
        for analysis in analyses:
            skill_name = analysis.get("skill_name", "Unknown Skill")
            analysis_text = analysis.get("analysis_text", "No detailed analysis available.")
            confidence = analysis.get("confidence_score", 0)
            status = analysis.get("status", "unknown")
            
            report += f"""
### {skill_name}

**Status:** {status.title()}  
**Confidence:** {confidence:.1%}

{analysis_text}

---

## """
        
        confidence_info = self._extract_confidence_info(analyses)
        
        report += f"""
## 📋 Analysis Summary

**Overall Confidence:** {confidence_info['average_confidence']:.1%}  
**Analyses Completed:** {len(analyses)}  

| Skill | Status | Confidence |
|-------|---------|------------|
"""
        
        for analysis in analyses:
            skill_name = analysis.get("skill_name", "Unknown")
            status = analysis.get("status", "unknown")
            confidence = analysis.get("confidence_score", 0)
            report += f"| {skill_name} | {status.title()} | {confidence:.1%} |\n"
        
        report += f"""

---

## 📊 Confidence Distribution

- **High Confidence (>80%):** {confidence_info['confidence_distribution']['high']} analyses
- **Medium Confidence (60-80%):** {confidence_info['confidence_distribution']['medium']} analyses  
- **Low Confidence (<60%):** {confidence_info['confidence_distribution']['low']} analyses

---

## ⚠️ Limitations

This report was generated using fallback synthesis due to technical issues with the advanced AI synthesis service. The analysis data is complete, but the narrative synthesis and cross-skill insights may be limited.

For the full synthesized report with executive summary and cross-skill insights, please try again later.

---

*Report generated by GetSmart AI Game Intelligence System (Fallback Mode)*
"""
        
        return report

    async def synthesize_master_analysis(self, master_json: Dict[str, Any]) -> SynthesisOutput:
        """
        Synthesize Master-JSON into comprehensive report.
        
        Args:
            master_json: Output from Phase 2 AI analysis
            
        Returns:
            SynthesisOutput with structured Markdown report
        """
        try:
            # Extract data from Master-JSON
            game_info = master_json.get("game_info", {})
            macro_skill_analyses = master_json.get("macro_skill_analyses", [])
            analysis_metadata = master_json.get("analysis_metadata", {})
            
            if isinstance(macro_skill_analyses, dict):
                normalized_analyses: list[dict[str, Any]] = []
                for skill_key, analysis_value in macro_skill_analyses.items():
                    if isinstance(analysis_value, dict):
                        analysis_entry = dict(analysis_value)
                        if "skill_name" not in analysis_entry:
                            analysis_entry["skill_name"] = skill_key.replace("_", " ").title()
                    else:
                        analysis_entry = {
                            "skill_name": skill_key.replace("_", " ").title(),
                            "analysis_text": str(analysis_value),
                        }
                    normalized_analyses.append(analysis_entry)
                macro_skill_analyses = normalized_analyses
            elif isinstance(macro_skill_analyses, list):
                normalized_analyses = []
                for analysis_entry in macro_skill_analyses:
                    if isinstance(analysis_entry, dict):
                        if "skill_name" not in analysis_entry:
                            metadata = analysis_entry.get("metadata", {})
                            analysis_entry = dict(analysis_entry)
                            if isinstance(metadata, dict) and metadata.get("skill_name"):
                                analysis_entry["skill_name"] = metadata.get("skill_name")
                        normalized_analyses.append(analysis_entry)
                    else:
                        normalized_analyses.append({"skill_name": "Unknown", "analysis_text": str(analysis_entry)})
                macro_skill_analyses = normalized_analyses

            game_name = game_info.get("game_name", "Unknown Game")
            game_id = game_info.get("game_id", "unknown")

            # Validate input data
            if not macro_skill_analyses:
                raise ValueError("No macro-skill analyses found in Master-JSON")
            
            # Create synthesis prompt
            formatted_analyses = self._format_macro_skill_analyses(macro_skill_analyses)
            
            synthesis_prompt = self.synthesis_prompt_template.format(
                game_name=game_name,
                timestamp=datetime.utcnow().strftime("%B %d, %Y"),
                macro_skill_analyses=formatted_analyses
            )
            
            logger.info("Calling Gemini for synthesis...")
            
            # Generate synthesis using Gemini
            synthesis_model = "gemini-1.5-flash"
            markdown_content = await self.gemini_client.generate_text(
                system_instruction="You are an expert game analyst and intelligence reporter.",
                user_prompt=synthesis_prompt,
                temperature=0.3,
            )

            markdown_content = markdown_content.strip()
            
            # Clean up the markdown
            if "```markdown" in markdown_content:
                markdown_content = markdown_content.split("```markdown")[1].split("```")[0]
            elif "```" in markdown_content:
                # Extract content between first and last ```
                parts = markdown_content.split("```")
                if len(parts) >= 2:
                    markdown_content = parts[1]
            
            # Extract confidence info
            confidence_info = self._extract_confidence_info(macro_skill_analyses)
            
            # Create synthesis analysis
            synthesis_analysis = SynthesisAnalysis(
                text=markdown_content,
                synthesis_confidence=confidence_info["average_confidence"],
                key_analyses=[analysis.get("skill_name", "Unknown") for analysis in macro_skill_analyses],
                synthesis_stats={
                    "analyses_input": len(macro_skill_analyses),
                    "synthesis_model": synthesis_model,
                    "word_count": len(markdown_content.split()),
                    "confidence_distribution": confidence_info["confidence_distribution"]
                }
            )
            
            # Create response
            synthesis_output = SynthesisOutput(
                status="success",
                synthesis=synthesis_analysis,
                game_name=game_name,
                game_id=game_id,
                synthesis_timestamp=datetime.utcnow().isoformat() + "Z",
                source_analyses_count=len(macro_skill_analyses),
                word_count=len(markdown_content.split()),
                metadata={
                    "source_master_json": master_json.get("game_info", {}),
                    "synthesis_version": "1.0.0",
                    "model_used": synthesis_model,
                    "confidence_metrics": confidence_info
                }
            )
            
            logger.info(f"✅ Synthesis completed for {game_name}")
            return synthesis_output
            
        except Exception as e:
            # Create error output with fallback report
            logger.error(f"❌ Synthesis failed for {game_name}: {str(e)}")
            
            fallback_report = self._create_fallback_report(master_json)
            
            return SynthesisOutput(
                status="partial_success",
                synthesis=SynthesisAnalysis(
                    text=fallback_report,
                    synthesis_confidence=0.5,
                    key_analyses=[],
                    synthesis_stats={"fallback_used": True, "error": str(e)}
                ),
                game_name=game_info.get("game_name", "Unknown"),
                game_id=game_info.get("game_id", "unknown"),
                synthesis_timestamp=datetime.utcnow().isoformat() + "Z",
                source_analyses_count=len(master_json.get("macro_skill_analyses", [])),
                word_count=len(fallback_report.split()),
                metadata={
                    "error": str(e),
                    "fallback_mode": True,
                    "synthesis_version": "1.0.0"
                }
            )

    def validate_synthesis_quality(self, synthesis_output: SynthesisOutput) -> Dict[str, Any]:
        """
        Validate the quality and completeness of synthesis output.
        
        Returns quality metrics and recommendations.
        """
        synthesis_text = synthesis_output.synthesis.text
        metadata = synthesis_output.metadata
        
        quality_metrics = {
            "structure_valid": True,
            "content_completeness": {},
            "readability_metrics": {},
            "recommendations": []
        }
        
        # Check for required sections
        required_sections = [
            "Executive Summary",
            "Design & Art Analysis", 
            "User Experience Analysis",
            "Technology Systems Analysis",
            "Strategy & Market Analysis",
            "Strategic Recommendations"
        ]
        
        for section in required_sections:
            section_found = section.lower() in synthesis_text.lower()
            quality_metrics["content_completeness"][section] = section_found
            
            if not section_found:
                quality_metrics["recommendations"].append(f"Add missing section: {section}")
        
        # Word count and length checks
        word_count = synthesis_output.word_count
        if word_count < 1000:
            quality_metrics["readability_metrics"]["word_count"] = "too_short"
            quality_metrics["recommendations"].append("Expand analysis with more detailed insights")
        elif word_count > 5000:
            quality_metrics["readability_metrics"]["word_count"] = "too_long"
            quality_metrics["recommendations"].append("Consider shortening for better readability")
        else:
            quality_metrics["readability_metrics"]["word_count"] = "appropriate"
        
        # Confidence assessment
        confidence = synthesis_output.synthesis.synthesis_confidence
        if confidence < 0.6:
            quality_metrics["recommendations"].append("Low confidence detected - consider review and refinement")
        
        # Overall quality score
        missing_sections = sum(1 for found in quality_metrics["content_completeness"].values() if not found)
        total_sections = len(required_sections)
        completeness_score = (total_sections - missing_sections) / total_sections
        
        if completeness_score >= 0.9:
            quality_metrics["overall_score"] = "high"
        elif completeness_score >= 0.7:
            quality_metrics["overall_score"] = "medium"
        else:
            quality_metrics["overall_score"] = "low"
            quality_metrics["recommendations"].append("Major content gaps detected - comprehensive revision recommended")
        
        return quality_metrics